// apps/web/src/components/LandingTable.svelte
<script lang="ts">
  import {
    filterAndSortNodes,
    type LandingNode,
    type SortDir,
    type SortField,
  } from "../lib/landing";
  import { DEFAULT_TAB, TABS, type Tab } from "../lib/category-map";
  import { PIZZA_SLICES, GRADE_FILL, GRADE_TOOLTIP, pizzaGradesFor, type PizzaGrades, type PizzaSize } from "../lib/pizza";
  import { EM_DASH, formatTvl } from "../lib/format";

  const DEFAULT_PAGE = 200;

  type Props = {
    nodes: LandingNode[];
    tabCounts: Record<Tab, number>;
  };

  let { nodes, tabCounts }: Props = $props();

  let tab = $state<Tab>(DEFAULT_TAB);
  let query = $state("");
  let showInactive = $state(false);
  let showAll = $state(false);
  let pizzaFilters = $state<Record<string, boolean>>({});
  let expanded = $state<Record<string, boolean>>({});
  let sortField = $state<SortField>("tvl");
  let sortDir = $state<SortDir>("desc");

  const searching = $derived(query.trim().length > 0);
  const filtered = $derived(
    filterAndSortNodes(nodes, {
      tab,
      query,
      showInactive,
      sort: { field: sortField, dir: sortDir },
    }),
  );
  const visible = $derived(showAll ? filtered : filtered.slice(0, DEFAULT_PAGE));
  const activePizzas = $derived(Object.keys(pizzaFilters).filter((k) => pizzaFilters[k]));
  const showSort = $derived(!searching);

  function onSortClick(field: SortField) {
    if (sortField === field) {
      sortDir = sortDir === "asc" ? "desc" : "asc";
    } else {
      sortField = field;
      sortDir = field === "tvl" ? "desc" : "asc";
    }
  }

  function arrow(field: SortField): string {
    const isActive = showSort && sortField === field;
    return isActive ? (sortDir === "asc" ? "\u2191" : "\u2193") : "\u2195";
  }

  function ariaSort(field: SortField): "ascending" | "descending" | "none" {
    const isActive = showSort && sortField === field;
    return isActive ? (sortDir === "asc" ? "ascending" : "descending") : "none";
  }

  function pizzaPaths(grades: PizzaGrades, size: PizzaSize) {
    const radius = size === "sm" ? 18 : 72;
    const stroke = size === "sm" ? 1 : 2;
    const cx = radius, cy = radius;
    const angle = (2 * Math.PI) / PIZZA_SLICES.length;
    return {
      radius,
      stroke,
      paths: PIZZA_SLICES.map((slice, i) => {
        const a0 = -Math.PI / 2 + i * angle;
        const a1 = a0 + angle;
        const x0 = cx + radius * Math.cos(a0);
        const y0 = cy + radius * Math.sin(a0);
        const x1 = cx + radius * Math.cos(a1);
        const y1 = cy + radius * Math.sin(a1);
        const grade = grades[slice.id] ?? "gray";
        return {
          id: slice.id,
          label: slice.label,
          d: `M${cx},${cy} L${x0},${y0} A${radius},${radius} 0 0,1 ${x1},${y1} Z`,
          fill: GRADE_FILL[grade],
          tooltip: GRADE_TOOLTIP[grade],
        };
      }),
    };
  }
</script>

<section>
  <nav class="tabs">
    {#each TABS as t}
      {@const active = t === tab}
      {@const count = tabCounts[t] ?? 0}
      <button
        type="button"
        aria-pressed={active}
        class:active
        onclick={() => { tab = t; showAll = false; }}
      >
        {t}<span class="count">{count.toLocaleString()}</span>
      </button>
    {/each}
  </nav>

  <div class="controls">
    <input
      type="search"
      aria-label="Search protocols by name, slug, or category"
      placeholder="Search name, slug, category"
      bind:value={query}
    />
    <label class="checkbox">
      <input type="checkbox" bind:checked={showInactive} />
      Show inactive
    </label>
  </div>

  <div class="chips">
    {#each PIZZA_SLICES as s}
      {@const on = !!pizzaFilters[s.id]}
      <button
        type="button"
        aria-pressed={on}
        class:on
        title={`${s.label} ${EM_DASH} all unknown at Phase 0`}
        onclick={() => { pizzaFilters = { ...pizzaFilters, [s.id]: !pizzaFilters[s.id] }; }}
      >
        {s.label}
      </button>
    {/each}
    {#if activePizzas.length > 0}
      <span class="chips-note">(filters are no-ops at Phase 0)</span>
    {/if}
  </div>

  <div class="scroll">
    <table>
      <thead>
        <tr>
          <th class="rank">#</th>
          <th class="sortable name-col">
            <button type="button" onclick={() => showSort && onSortClick("name")} disabled={!showSort} aria-sort={ariaSort("name")}
              class:is-active={showSort && sortField === "name"}>
              Name<span class="arrow">{arrow("name")}</span>
            </button>
          </th>
          <th class="sortable">
            <button type="button" onclick={() => showSort && onSortClick("chain")} disabled={!showSort} aria-sort={ariaSort("chain")}
              class:is-active={showSort && sortField === "chain"}>
              Chain<span class="arrow">{arrow("chain")}</span>
            </button>
          </th>
          <th>Risks</th>
          <th>Stage</th>
          <th class="sortable">
            <button type="button" onclick={() => showSort && onSortClick("type")} disabled={!showSort} aria-sort={ariaSort("type")}
              class:is-active={showSort && sortField === "type"}>
              Type<span class="arrow">{arrow("type")}</span>
            </button>
          </th>
          <th class="sortable right">
            <button type="button" onclick={() => showSort && onSortClick("tvl")} disabled={!showSort} aria-sort={ariaSort("tvl")}
              class:is-active={showSort && sortField === "tvl"}>
              TVL<span class="arrow">{arrow("tvl")}</span>
            </button>
          </th>
        </tr>
      </thead>
      <tbody>
        {#each visible as node, i (node.slug)}
          {@const isFamily = !!(node.children && node.children.length > 0)}
          {@const isExp = !!expanded[node.slug]}
          {@render row(i + 1, node, isFamily, isExp, false)}
          {#if isFamily && isExp}
            {#each node.children ?? [] as child (child.slug)}
              {@render row(null, child, false, false, true)}
            {/each}
          {/if}
        {/each}
      </tbody>
    </table>
  </div>

  <div class="pager">
    <span class="muted">Showing {visible.length.toLocaleString()} of {filtered.length.toLocaleString()}</span>
    {#if filtered.length > DEFAULT_PAGE}
      <button type="button" class="show-all" onclick={() => { showAll = !showAll; }}>
        {showAll ? "Collapse to top 200" : "Show all"}
      </button>
    {/if}
  </div>
</section>

{#snippet row(rank: number | null, row: LandingNode, isFamilyHead: boolean, isExpanded: boolean, isChild: boolean)}
  {@const extraChains = Math.max(0, row.chains.length - 1)}
  {@const grades = pizzaGradesFor(row.category, row.verifiability_grade, row.dependencies_grade)}
  {@const pz = pizzaPaths(grades, "sm")}
  {@const initial = row.name.charAt(0).toUpperCase()}
  <tr class:child={isChild}>
    <td class="rank-cell">{rank ?? ""}</td>
    <td class="name-cell" class:child-cell={isChild}>
      {#if isFamilyHead}
        <button
          type="button"
          onclick={() => { expanded = { ...expanded, [row.slug]: !expanded[row.slug] }; }}
          aria-expanded={isExpanded}
          aria-label={isExpanded ? "Collapse family" : "Expand family"}
          class="toggle"
        >{isExpanded ? "\u25BE" : "\u25B8"}</button>
      {:else if !isChild}
        <span class="toggle-placeholder" aria-hidden="true"></span>
      {/if}
      <span class="logo" aria-hidden="true" style="width:20px;height:20px;font-size:11px">
        {initial}
        {#if row.logo}
          <img src={row.logo} alt="" loading="lazy" decoding="async" width="20" height="20" />
        {/if}
      </span>
      <a href={`/protocol/${row.slug}`} class="name-link">{row.name}</a>
      {#if isFamilyHead}
        <span class="muted small-pad">({row.children?.length ?? 0})</span>
      {/if}
      {#if row.is_dead}
        <span class="muted small-pad">(inactive)</span>
      {/if}
    </td>
    <td>
      {row.primary_chain ?? EM_DASH}
      {#if extraChains > 0}
        <span class="extra-chains">+{extraChains}</span>
      {/if}
    </td>
    <td class="pizza-cell">
      <svg width={pz.radius * 2} height={pz.radius * 2} viewBox={`0 0 ${pz.radius * 2} ${pz.radius * 2}`} role="img" aria-label="risk pizza (all unknown)">
        {#each pz.paths as p}
          <a href="/methodology#what-is-graded-today">
            <path d={p.d} fill={p.fill} stroke="#08090c" stroke-width={pz.stroke}>
              <title>{`${p.label} \u2014 ${p.tooltip}`}</title>
            </path>
          </a>
        {/each}
      </svg>
    </td>
    <td class="muted">{EM_DASH}</td>
    <td>{row.category || EM_DASH}</td>
    <td class="tvl mono tabular">{formatTvl(row.tvl)}</td>
  </tr>
{/snippet}

<style>
  section { display: block; }
  .tabs {
    display: flex;
    gap: 0.25rem;
    flex-wrap: wrap;
    margin-bottom: 1rem;
  }
  .tabs button {
    min-height: 44px;
    padding: 0 0.9rem;
    border: none;
    border-radius: 4px;
    background: var(--surface-raised);
    color: var(--text);
    cursor: pointer;
    font-size: 0.85rem;
  }
  .tabs button.active { background: var(--accent-link); color: var(--bg); }
  .count { opacity: 0.6; margin-left: 4px; }
  .controls {
    display: flex;
    gap: 0.75rem;
    flex-wrap: wrap;
    margin-bottom: 0.75rem;
    align-items: center;
  }
  .controls input[type="search"] {
    flex: 1 1 18rem;
    min-height: 44px;
    padding: 0 0.75rem;
    background: var(--bg);
    color: var(--text);
    border: 1px solid var(--surface-raised);
    border-radius: 4px;
    font-size: 0.9rem;
  }
  .checkbox {
    display: flex;
    gap: 0.5rem;
    align-items: center;
    color: var(--text-muted);
    font-size: 0.85rem;
  }
  .chips {
    display: flex;
    gap: 0.35rem;
    flex-wrap: wrap;
    margin-bottom: 1rem;
  }
  .chips button {
    min-height: 44px;
    padding: 0 0.9rem;
    border: 1px solid var(--surface-raised);
    border-radius: 999px;
    background: transparent;
    color: var(--text-muted);
    font-size: 0.75rem;
    cursor: pointer;
  }
  .chips button.on { background: var(--accent-link); color: var(--bg); }
  .chips-note {
    color: var(--text-muted);
    font-size: 0.75rem;
    align-self: center;
    margin-left: 0.5rem;
  }
  .scroll { overflow-x: auto; }
  table {
    width: 100%;
    border-collapse: collapse;
    color: var(--text);
    font-size: 0.9rem;
  }
  thead tr { text-align: left; color: var(--text-muted); font-size: 0.8rem; }
  th { padding: 0.45rem 0.6rem; font-weight: 500; }
  th.rank { width: 3rem; }
  th.sortable { padding: 0; }
  th.right { text-align: right; }
  th.sortable button {
    background: transparent;
    border: none;
    padding: 0.45rem 0.6rem;
    min-height: 44px;
    width: 100%;
    text-align: left;
    color: var(--text-muted);
    cursor: pointer;
    font-size: 0.8rem;
    font-weight: 500;
    opacity: 0.5;
  }
  th.sortable button:enabled { opacity: 1; }
  th.sortable button.is-active { color: var(--text); }
  th.sortable.right button { text-align: right; }
  th.name-col button { padding-left: calc(0.6rem + 44px + 6px); }
  .arrow { margin-left: 4px; opacity: 0.4; }
  th.sortable button.is-active .arrow { opacity: 1; }
  tbody tr { border-top: 1px solid var(--surface-raised); }
  tbody tr.child { background: var(--surface); }
  td { padding: 0.45rem 0.6rem; }
  .rank-cell { color: var(--text-muted); }
  .name-cell.child-cell { padding-left: 2rem; }
  .toggle {
    box-sizing: border-box;
    background: transparent;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
    margin-right: 6px;
    padding: 0.6rem;
    min-width: 44px;
    min-height: 44px;
    font-size: 0.85rem;
    text-align: center;
    vertical-align: middle;
  }
  .toggle-placeholder {
    display: inline-block;
    width: 44px;
    margin-right: 6px;
    vertical-align: middle;
  }
  .logo {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 4px;
    background: var(--surface-raised);
    color: var(--text-muted);
    font-weight: 500;
    flex-shrink: 0;
    overflow: hidden;
    position: relative;
    vertical-align: middle;
  }
  .logo img {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .name-link { text-decoration: none; margin-left: 8px; color: var(--accent-link); }
  .muted { color: var(--text-muted); }
  .small-pad { margin-left: 6px; font-size: 0.75rem; }
  .extra-chains {
    margin-left: 6px;
    padding: 0 0.4rem;
    background: var(--surface-raised);
    border-radius: 999px;
    color: var(--text-muted);
    font-size: 0.7rem;
  }
  .pizza-cell { padding: 0.2rem 0.6rem; }
  .tvl {
    text-align: right;
    font-family: var(--font-mono), ui-monospace, monospace;
    font-variant-numeric: tabular-nums;
  }
  .pager {
    margin-top: 1rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  .show-all {
    background: transparent;
    border: 1px solid var(--surface-raised);
    color: var(--accent-link);
    min-height: 44px;
    padding: 0 0.9rem;
    border-radius: 4px;
    cursor: pointer;
    font-size: 0.85rem;
  }
</style>

// apps/web/src/components/LandingTable.tsx
"use client";

import { useMemo, useState, Fragment } from "react";
import {
  filterAndSortNodes,
  type LandingNode,
  type LandingRow,
  type SortDir,
  type SortField,
} from "../lib/landing";
import { DEFAULT_TAB, TABS, type Tab } from "../lib/category-map";
import { PIZZA_SLICES, PizzaChart } from "./PizzaChart";
import { ProtocolLogo } from "./ProtocolLogo";
import { EM_DASH, formatTvl } from "../lib/format";
import { pizzaGradesFor } from "../lib/pizza";

const DEFAULT_PAGE = 200;

type Props = {
  nodes: LandingNode[];
  tabCounts: Record<Tab, number>;
};

export function LandingTable({ nodes, tabCounts }: Props) {
  const [tab, setTab] = useState<Tab>(DEFAULT_TAB);
  const [query, setQuery] = useState("");
  const [showInactive, setShowInactive] = useState(false);
  const [showAll, setShowAll] = useState(false);
  const [pizzaFilters, setPizzaFilters] = useState<Record<string, boolean>>({});
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});
  const [sortField, setSortField] = useState<SortField>("tvl");
  const [sortDir, setSortDir] = useState<SortDir>("desc");

  const searching = query.trim().length > 0;
  const filtered = useMemo(
    () =>
      filterAndSortNodes(nodes, {
        tab,
        query,
        showInactive,
        sort: { field: sortField, dir: sortDir },
      }),
    [nodes, tab, query, showInactive, sortField, sortDir],
  );

  function onSortClick(field: SortField) {
    if (sortField === field) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortField(field);
      setSortDir(field === "tvl" ? "desc" : "asc");
    }
  }

  const visible = showAll ? filtered : filtered.slice(0, DEFAULT_PAGE);
  const activePizzas = Object.keys(pizzaFilters).filter((k) => pizzaFilters[k]);
  const showSort = !searching;

  return (
    <section>
      <nav style={{ display: "flex", gap: "0.25rem", flexWrap: "wrap", marginBottom: "1rem" }}>
        {TABS.map((t) => {
          const active = t === tab;
          const count = tabCounts[t] ?? 0;
          return (
            <button
              key={t}
              type="button"
              aria-pressed={active}
              onClick={() => {
                setTab(t);
                setShowAll(false);
              }}
              style={{
                minHeight: 44,
                padding: "0 0.9rem",
                border: "none",
                borderRadius: 4,
                background: active ? "var(--accent-link)" : "var(--surface-raised)",
                color: active ? "var(--bg)" : "var(--text)",
                cursor: "pointer",
                fontSize: "0.85rem",
              }}
            >
              {t} <span style={{ opacity: 0.6, marginLeft: 4 }}>{count.toLocaleString()}</span>
            </button>
          );
        })}
      </nav>

      <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap", marginBottom: "0.75rem", alignItems: "center" }}>
        <input
          type="search"
          aria-label="Search protocols by name, slug, or category"
          placeholder="Search name, slug, category"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          style={{
            flex: "1 1 18rem",
            minHeight: 44,
            padding: "0 0.75rem",
            background: "var(--bg)",
            color: "var(--text)",
            border: "1px solid var(--surface-raised)",
            borderRadius: 4,
            fontSize: "0.9rem",
          }}
        />
        <label style={{ display: "flex", gap: "0.5rem", alignItems: "center", color: "var(--text-muted)", fontSize: "0.85rem" }}>
          <input
            type="checkbox"
            checked={showInactive}
            onChange={(e) => setShowInactive(e.target.checked)}
          />
          Show inactive
        </label>
      </div>

      <div style={{ display: "flex", gap: "0.35rem", flexWrap: "wrap", marginBottom: "1rem" }}>
        {PIZZA_SLICES.map((s) => {
          const on = !!pizzaFilters[s.id];
          return (
            <button
              key={s.id}
              type="button"
              aria-pressed={on}
              onClick={() => setPizzaFilters((prev) => ({ ...prev, [s.id]: !prev[s.id] }))}
              title={`${s.label} ${EM_DASH} all unknown at Phase 0`}
              style={{
                minHeight: 44,
                padding: "0 0.9rem",
                border: "1px solid var(--surface-raised)",
                borderRadius: 999,
                background: on ? "var(--accent-link)" : "transparent",
                color: on ? "var(--bg)" : "var(--text-muted)",
                fontSize: "0.75rem",
                cursor: "pointer",
              }}
            >
              {s.label}
            </button>
          );
        })}
        {activePizzas.length > 0 ? (
          <span style={{ color: "var(--text-muted)", fontSize: "0.75rem", alignSelf: "center", marginLeft: "0.5rem" }}>
            (filters are no-ops at Phase 0)
          </span>
        ) : null}
      </div>

      <div style={{ overflowX: "auto" }}>
      <table style={{ width: "100%", borderCollapse: "collapse", color: "var(--text)", fontSize: "0.9rem" }}>
        <thead>
          <tr style={{ textAlign: "left", color: "var(--text-muted)", fontSize: "0.8rem" }}>
            <th style={{ padding: "0.45rem 0.6rem", width: "3rem" }}>#</th>
            <SortableHeader
              label="Name"
              field="name"
              sortField={sortField}
              sortDir={sortDir}
              onClick={onSortClick}
              active={showSort}
              paddingLeft="calc(0.6rem + 44px + 6px)"
            />
            <SortableHeader
              label="Chain"
              field="chain"
              sortField={sortField}
              sortDir={sortDir}
              onClick={onSortClick}
              active={showSort}
            />
            <th style={{ padding: "0.45rem 0.6rem" }}>Risks</th>
            <th style={{ padding: "0.45rem 0.6rem" }}>Stage</th>
            <SortableHeader
              label="Type"
              field="type"
              sortField={sortField}
              sortDir={sortDir}
              onClick={onSortClick}
              active={showSort}
            />
            <SortableHeader
              label="TVL"
              field="tvl"
              sortField={sortField}
              sortDir={sortDir}
              onClick={onSortClick}
              active={showSort}
              align="right"
            />
          </tr>
        </thead>
        <tbody>
          {visible.map((node, i) => {
            const isFamily = !!(node.children && node.children.length > 0);
            const isExpanded = !!expanded[node.slug];
            return (
              <Fragment key={node.slug}>
                <Row
                  rank={i + 1}
                  row={node}
                  isFamilyHead={isFamily}
                  isExpanded={isExpanded}
                  onToggle={() =>
                    setExpanded((prev) => ({ ...prev, [node.slug]: !prev[node.slug] }))
                  }
                />
                {isFamily && isExpanded
                  ? (node.children ?? []).map((child) => (
                      <Row key={child.slug} rank={null} row={child} isChild />
                    ))
                  : null}
              </Fragment>
            );
          })}
        </tbody>
      </table>
      </div>

      <div style={{ marginTop: "1rem", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span style={{ color: "var(--text-muted)", fontSize: "0.85rem" }}>
          Showing {visible.length.toLocaleString()} of {filtered.length.toLocaleString()}
        </span>
        {filtered.length > DEFAULT_PAGE ? (
          <button
            type="button"
            onClick={() => setShowAll((v) => !v)}
            style={{
              background: "transparent",
              border: "1px solid var(--surface-raised)",
              color: "var(--accent-link)",
              minHeight: 44,
              padding: "0 0.9rem",
              borderRadius: 4,
              cursor: "pointer",
              fontSize: "0.85rem",
            }}
          >
            {showAll ? "Collapse to top 200" : "Show all"}
          </button>
        ) : null}
      </div>
    </section>
  );
}

type SortableHeaderProps = {
  label: string;
  field: SortField;
  sortField: SortField;
  sortDir: SortDir;
  onClick: (field: SortField) => void;
  active: boolean;
  align?: "left" | "right";
  paddingLeft?: string;
};

function SortableHeader({ label, field, sortField, sortDir, onClick, active, align = "left", paddingLeft }: SortableHeaderProps) {
  const isActive = active && sortField === field;
  const arrow = isActive ? (sortDir === "asc" ? "\u2191" : "\u2193") : "\u2195";
  return (
    <th style={{ padding: 0, textAlign: align }}>
      <button
        type="button"
        onClick={() => active && onClick(field)}
        disabled={!active}
        aria-sort={isActive ? (sortDir === "asc" ? "ascending" : "descending") : "none"}
        style={{
          background: "transparent",
          border: "none",
          padding: "0.45rem 0.6rem",
          paddingLeft: paddingLeft ?? "0.6rem",
          minHeight: 44,
          width: "100%",
          textAlign: align,
          color: isActive ? "var(--text)" : "var(--text-muted)",
          cursor: active ? "pointer" : "default",
          fontSize: "0.8rem",
          fontWeight: 500,
          opacity: active ? 1 : 0.5,
        }}
      >
        {label}
        <span style={{ marginLeft: 4, opacity: isActive ? 1 : 0.4 }}>{arrow}</span>
      </button>
    </th>
  );
}

type RowProps = {
  rank: number | null;
  row: LandingNode;
  isFamilyHead?: boolean;
  isExpanded?: boolean;
  onToggle?: () => void;
  isChild?: boolean;
};

function Row({ rank, row, isFamilyHead, isExpanded, onToggle, isChild }: RowProps) {
  const extraChains = Math.max(0, row.chains.length - 1);
  return (
    <tr
      style={{
        borderTop: "1px solid var(--surface-raised)",
        background: isChild ? "var(--surface)" : undefined,
      }}
    >
      <td style={{ padding: "0.45rem 0.6rem", color: "var(--text-muted)" }}>{rank ?? ""}</td>
      <td style={{ padding: "0.45rem 0.6rem", paddingLeft: isChild ? "2rem" : "0.6rem" }}>
        {isFamilyHead ? (
          <button
            type="button"
            onClick={onToggle}
            aria-expanded={isExpanded}
            aria-label={isExpanded ? "Collapse family" : "Expand family"}
            style={{
              boxSizing: "border-box",
              background: "transparent",
              border: "none",
              color: "var(--text-muted)",
              cursor: "pointer",
              marginRight: 6,
              padding: "0.6rem",
              minWidth: 44,
              minHeight: 44,
              fontSize: "0.85rem",
              textAlign: "center",
              verticalAlign: "middle",
            }}
          >
            {isExpanded ? "\u25BE" : "\u25B8"}
          </button>
        ) : !isChild ? (
          <span
            aria-hidden
            style={{ display: "inline-block", width: 44, marginRight: 6, verticalAlign: "middle" }}
          />
        ) : null}
        <ProtocolLogo src={row.logo} name={row.name} size={20} />
        <a href={`/protocol/${row.slug}`} style={{ textDecoration: "none", marginLeft: 8 }}>
          {row.name}
        </a>
        {isFamilyHead ? (
          <span style={{ color: "var(--text-muted)", marginLeft: 6, fontSize: "0.75rem" }}>
            ({row.children?.length ?? 0})
          </span>
        ) : null}
        {row.is_dead ? (
          <span style={{ color: "var(--text-muted)", marginLeft: 6, fontSize: "0.75rem" }}>(inactive)</span>
        ) : null}
      </td>
      <td style={{ padding: "0.45rem 0.6rem" }}>
        {row.primary_chain ?? EM_DASH}
        {extraChains > 0 ? (
          <span
            style={{
              marginLeft: 6,
              padding: "0 0.4rem",
              background: "var(--surface-raised)",
              borderRadius: 999,
              color: "var(--text-muted)",
              fontSize: "0.7rem",
            }}
          >
            +{extraChains}
          </span>
        ) : null}
      </td>
      <td style={{ padding: "0.2rem 0.6rem" }}>
        <PizzaChart
          size="sm"
          grades={pizzaGradesFor(row.category, row.verifiability_grade, row.dependencies_grade)}
        />
      </td>
      <td style={{ padding: "0.45rem 0.6rem", color: "var(--text-muted)" }}>{EM_DASH}</td>
      <td style={{ padding: "0.45rem 0.6rem" }}>{row.category || EM_DASH}</td>
      <td style={{ padding: "0.45rem 0.6rem", textAlign: "right", fontFamily: "var(--font-mono), ui-monospace, monospace", fontVariantNumeric: "tabular-nums" }}>{formatTvl(row.tvl)}</td>
    </tr>
  );
}
